version: "2"

linters:
  enable:
    - gosec
  exclusions:
    warn-unused: true
    presets:
      - common-false-positives
      - std-error-handling

formatters:
  enable:
    - gci
    - gofumpt

  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
